import sqlite3

db = sqlite3.connect("sofka_challenge.sqlite")

# Table Category
db.execute("CREATE TABLE IF NOT EXISTS Category (Id INTEGER, Category_name TEXT, Points INTEGER, Level INTEGER)")
db.execute("DELETE FROM Category")  #TODO Remove
db.execute("INSERT INTO Category VALUES(1, 'Categoria 1', 10, 1)")
db.execute("INSERT INTO Category VALUES(2, 'Categoria 2', 20, 2)")
db.execute("INSERT INTO Category VALUES(3, 'Categoria 3', 30, 3)")
db.execute("INSERT INTO Category VALUES(4, 'Categoria 4', 40, 4)")
db.execute("INSERT INTO Category VALUES(5, 'Categoria 5', 100, 5)")

# Table Questions
db.execute("CREATE TABLE IF NOT EXISTS Questions (Id INTEGER, Question TEXT, Category_id INTEGER)")
db.execute("DELETE FROM Questions")  #TODO Remove
db.execute("INSERT INTO Questions VALUES(1, '¿Qué palabra aparece tradicionalmente en la pantalla al terminar"
           " un largometraje?', 1)")
db.execute("INSERT INTO Questions VALUES(2, '¿Cuál de los siguientes sería atraído por un imán?', 1)")
db.execute("INSERT INTO Questions VALUES(3, '¿Qué palabra se usa para referirse a los abdominales bien marcados?', 1)")
db.execute("INSERT INTO Questions VALUES(4, '¿Cuál de estos nombres no aparece en el título de una "
           "obra de Shakespeare?', 1)")
db.execute("INSERT INTO Questions VALUES(5, '¿Cuál es el lugar de origen del whisky escocés?', 1)")
db.execute("INSERT INTO Questions VALUES(6, 'En los hoteles elegantes, "
           "¿qué snack suele dejarse sobre las almohadas?', 2)")
db.execute("INSERT INTO Questions VALUES(7, '¿Cuáles de estas aplicaciones ofrecen "
           "más o menos el mismo tipo de servicio?', 2)")
db.execute("INSERT INTO Questions VALUES(8, 'Cuando algo se encuentra "
           "en un lugar muy obvio, se dice que está abajo...', 2)")
db.execute("INSERT INTO Questions VALUES(9, '¿Para convencerte de que dice la verdad, "
           "una persona puede decir que lo juraría...?', 2)")
db.execute("INSERT INTO Questions VALUES(10, 'Por definición, "
           "¿qué tiene una bicicleta de 10 velocidades?', 2)")
db.execute("INSERT INTO Questions VALUES(11, '¿Cómo se llama la parte que queda en "
           "el suelo después de talar un árbol?', 3)")
db.execute("INSERT INTO Questions VALUES(12, 'En los libros de historia, "
           "¿qué título halagador comparten los líderes Alejandro y Catalina??', 3)")
db.execute("INSERT INTO Questions VALUES(13, '¿Qué planta es el símbolo nacional de Irlanda?', 3)")
db.execute("INSERT INTO Questions VALUES(14, '¿Cuál de estos es un instrumento musical?', 3)")
db.execute("INSERT INTO Questions VALUES(15, '¿Qué frase se usa para describir a"
           " especies animales que podrían desaparecer?', 3)")
db.execute("INSERT INTO Questions VALUES(16, '¿Finn y Jake, son los protagonistas de?', 4)")
db.execute("INSERT INTO Questions VALUES(17, '¿En la película de Disney; Tambor, el amigo de Bambi, es un?', 4)")
db.execute("INSERT INTO Questions VALUES(18, '¿Según el cuento de la Ceniciente, el Hada Madrina convirtió la"
           " calabaza en?', 4)")
db.execute("INSERT INTO Questions VALUES(19, '¿Qué es el punto G?', 4)")
db.execute("INSERT INTO Questions VALUES(20, 'Según el título de una novela de "
           "Gabriel García Márquez ¿quién no tiene quien le escriba??', 4)")
db.execute("INSERT INTO Questions VALUES(21, '¿Cual es el verdadero nombre de ALF?', 5)")
db.execute("INSERT INTO Questions VALUES(22, '¿La nectarina es?', 5)")
db.execute("INSERT INTO Questions VALUES(23, '¿Cuantas son las reliquias de la Muerte en Harry Potter?', 5)")
db.execute("INSERT INTO Questions VALUES(24, '¿Cual de estas personas no es un Flash de DC?', 5)")
db.execute("INSERT INTO Questions VALUES(25, '¿Qué edad tenía Drew Barrymore cuando protagonizó la película E.T.?', 5)")

# Table Answers
db.execute("CREATE TABLE IF NOT EXISTS Answers (Id INTEGER, Answer TEXT, Correct TEXT, Question_id INTEGER)")
db.execute("DELETE FROM Answers")  #TODO Remove
db.execute("INSERT INTO Answers VALUES(1, 'Fin', 'True', 1)")
db.execute("INSERT INTO Answers VALUES(2, 'Conclusión', 'False', 1)")
db.execute("INSERT INTO Answers VALUES(3, 'Finales', 'False', 1)")
db.execute("INSERT INTO Answers VALUES(4, 'Casi que no', 'False', 1)")
db.execute("INSERT INTO Answers VALUES(5, 'Madera', 'False', 2)")
db.execute("INSERT INTO Answers VALUES(6, 'Plastico', 'False', 2)")
db.execute("INSERT INTO Answers VALUES(7, 'Carne', 'False', 2)")
db.execute("INSERT INTO Answers VALUES(8, 'Metal', 'True', 2)")
db.execute("INSERT INTO Answers VALUES(9, 'Lavadora', 'False', 3)")
db.execute("INSERT INTO Answers VALUES(10, 'Chocolatina', 'True', 3)")
db.execute("INSERT INTO Answers VALUES(11, 'Carro', 'False', 3)")
db.execute("INSERT INTO Answers VALUES(12, 'Oceano', 'False', 3)")
db.execute("INSERT INTO Answers VALUES(13, 'Hamlet', 'False', 4)")
db.execute("INSERT INTO Answers VALUES(44, 'Romeo', 'False', 4)")
db.execute("INSERT INTO Answers VALUES(15, 'Macbeth', 'False', 4)")
db.execute("INSERT INTO Answers VALUES(16, 'Don Quijote', 'True', 4)")
db.execute("INSERT INTO Answers VALUES(17, 'Irlanda', 'False', 5)")
db.execute("INSERT INTO Answers VALUES(18, 'Gales', 'False', 5)")
db.execute("INSERT INTO Answers VALUES(19, 'Escocia', 'True', 5)")
db.execute("INSERT INTO Answers VALUES(20, 'Estados Unidos', 'False', 5)")
db.execute("INSERT INTO Answers VALUES(21, 'Un dulce', 'True', 6)")
db.execute("INSERT INTO Answers VALUES(22, 'La cuenta', 'False', 6)")
db.execute("INSERT INTO Answers VALUES(23, 'Un sanduche', 'False', 6)")
db.execute("INSERT INTO Answers VALUES(24, 'Las llaves', 'False', 6)")
db.execute("INSERT INTO Answers VALUES(25, 'Snapchat y Grubhub', 'False', 7)")
db.execute("INSERT INTO Answers VALUES(26, 'Whatsapp y SHAREit', 'False', 7)")
db.execute("INSERT INTO Answers VALUES(27, 'TikTok y Spotify', 'False', 7)")
db.execute("INSERT INTO Answers VALUES(28, 'Uber y DiDi', 'True', 7)")
db.execute("INSERT INTO Answers VALUES(29, 'Del colchón', 'False', 8)")
db.execute("INSERT INTO Answers VALUES(30, 'De tus narices', 'True', 8)")
db.execute("INSERT INTO Answers VALUES(31, 'De las axilas', 'False', 8)")
db.execute("INSERT INTO Answers VALUES(32, 'De tus bóxers', 'False', 8)")
db.execute("INSERT INTO Answers VALUES(33, 'Por el oro', 'False', 9)")
db.execute("INSERT INTO Answers VALUES(34, 'Por mi amor', 'False', 9)")
db.execute("INSERT INTO Answers VALUES(35, 'Por el medio ambiente', 'False', 9)")
db.execute("INSERT INTO Answers VALUES(36, 'Por Dios', 'True', 9)")
db.execute("INSERT INTO Answers VALUES(37, '10 Ruedas', 'False', 10)")
db.execute("INSERT INTO Answers VALUES(38, '10 Rayos', 'False', 10)")
db.execute("INSERT INTO Answers VALUES(39, '10 piñones', 'True', 10)")
db.execute("INSERT INTO Answers VALUES(40, '10 Vidas', 'False', 10)")
db.execute("INSERT INTO Answers VALUES(41, 'Muñon', 'False', 11)")
db.execute("INSERT INTO Answers VALUES(42, 'Joroba', 'False', 11)")
db.execute("INSERT INTO Answers VALUES(43, 'Tocón', 'True', 11)")
db.execute("INSERT INTO Answers VALUES(44, 'restos', 'False', 11)")
db.execute("INSERT INTO Answers VALUES(45, 'El/La Feroz', 'False', 12)")
db.execute("INSERT INTO Answers VALUES(46, 'El/La Grande', 'True', 12)")
db.execute("INSERT INTO Answers VALUES(47, 'El/La Rebelde', 'False', 12)")
db.execute("INSERT INTO Answers VALUES(48, 'El/La Ecoconsciente', 'False', 12)")
db.execute("INSERT INTO Answers VALUES(49, 'Cardo', 'False', 13)")
db.execute("INSERT INTO Answers VALUES(50, 'Rosa', 'False', 13)")
db.execute("INSERT INTO Answers VALUES(51, 'Puerro', 'False', 13)")
db.execute("INSERT INTO Answers VALUES(52, 'Trebol', 'True', 13)")
db.execute("INSERT INTO Answers VALUES(53, 'Mandrágora', 'False', 14)")
db.execute("INSERT INTO Answers VALUES(54, 'Mandalay', 'False', 14)")
db.execute("INSERT INTO Answers VALUES(55, 'Mandolina', 'True', 14)")
db.execute("INSERT INTO Answers VALUES(56, 'Mandril', 'False', 14)")
db.execute("INSERT INTO Answers VALUES(57, 'Bajo riesgo', 'False', 15)")
db.execute("INSERT INTO Answers VALUES(58, 'Bajo amenaza', 'False', 15)")
db.execute("INSERT INTO Answers VALUES(59, 'En peligro de extinción', 'True', 15)")
db.execute("INSERT INTO Answers VALUES(60, 'Peligradas', 'False', 15)")
db.execute("INSERT INTO Answers VALUES(61, 'Un Show más', 'False', 16)")
db.execute("INSERT INTO Answers VALUES(62, 'Hora de Aventura', 'True', 16)")
db.execute("INSERT INTO Answers VALUES(63, 'Más allá del Jardín', 'False', 16)")
db.execute("INSERT INTO Answers VALUES(64, 'Jake y los piratas', 'False', 16)")
db.execute("INSERT INTO Answers VALUES(65, 'Gato', 'False', 17)")
db.execute("INSERT INTO Answers VALUES(66, 'Conejo', 'True', 17)")
db.execute("INSERT INTO Answers VALUES(67, 'Elefante', 'False', 17)")
db.execute("INSERT INTO Answers VALUES(68, 'Perro', 'False', 17)")
db.execute("INSERT INTO Answers VALUES(69, 'Cenizas', 'False', 18)")
db.execute("INSERT INTO Answers VALUES(70, 'Carruaje', 'True', 18)")
db.execute("INSERT INTO Answers VALUES(71, 'Sapo', 'False', 18)")
db.execute("INSERT INTO Answers VALUES(72, 'Zapatillas', 'False', 18)")
db.execute("INSERT INTO Answers VALUES(73, 'Zona femenina muy sensible', 'True', 19)")
db.execute("INSERT INTO Answers VALUES(74, 'Botón para activar la bomba H', 'False', 19)")
db.execute("INSERT INTO Answers VALUES(75, 'Centro de gravedad universal', 'False', 19)")
db.execute("INSERT INTO Answers VALUES(76, 'Epicentro de un terremoto', 'False', 19)")
db.execute("INSERT INTO Answers VALUES(77, 'El Comandante', 'False', 20)")
db.execute("INSERT INTO Answers VALUES(78, 'El Coronel', 'True', 20)")
db.execute("INSERT INTO Answers VALUES(79, 'El Sargento', 'False', 20)")
db.execute("INSERT INTO Answers VALUES(80, 'El Mayor', 'False', 20)")
db.execute("INSERT INTO Answers VALUES(81, 'Alex Luciano Fernando', 'False', 21)")
db.execute("INSERT INTO Answers VALUES(82, 'El tomacorriente', 'False', 21)")
db.execute("INSERT INTO Answers VALUES(83, 'El come Gatos', 'False', 21)")
db.execute("INSERT INTO Answers VALUES(84, 'Gordon Shumway', 'True', 21)")
db.execute("INSERT INTO Answers VALUES(85, 'Una enzima', 'False', 22)")
db.execute("INSERT INTO Answers VALUES(86, 'Una fruta', 'True', 22)")
db.execute("INSERT INTO Answers VALUES(87, 'Un insecto', 'False', 22)")
db.execute("INSERT INTO Answers VALUES(88, 'Una hormona', 'False', 22)")
db.execute("INSERT INTO Answers VALUES(89, '3', 'True', 23)")
db.execute("INSERT INTO Answers VALUES(90, '4', 'False', 23)")
db.execute("INSERT INTO Answers VALUES(91, '2', 'False', 23)")
db.execute("INSERT INTO Answers VALUES(92, '5', 'False', 23)")
db.execute("INSERT INTO Answers VALUES(93, 'Wally West', 'False', 24)")
db.execute("INSERT INTO Answers VALUES(94, 'Jay Garrick', 'False', 24)")
db.execute("INSERT INTO Answers VALUES(95, 'Hal Jordan', 'True', 24)")
db.execute("INSERT INTO Answers VALUES(96, 'Barry Allen', 'False', 24)")
db.execute("INSERT INTO Answers VALUES(97, '7', 'False', 25)")
db.execute("INSERT INTO Answers VALUES(98, '9', 'False', 25)")
db.execute("INSERT INTO Answers VALUES(99, '6', 'True', 25)")
db.execute("INSERT INTO Answers VALUES(100, '8', 'False', 25)")

# Table Users
db.execute("CREATE TABLE IF NOT EXISTS Users (Name TEXT, Points INTEGER)")
# db.execute("DELETE FROM Users")  #TODO Remove


# Commit and Close
db.commit()
db.close()